name: minecraft-modded
services:
  minecraft-server:
    image: itzg/minecraft-server:java${JAVA_VERSION}
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "${QUERY_PORT}:25565"
      - "${VOICE_CHAT_PORT}:24454/udp"
    environment:
      EULA: "true"
      TZ: "America/Bogota"
      USE_AIKAR_FLAGS: "true"
      MEMORY: "${MEMORY}G"
      ENABLE_ROLLING_LOGS: "true"
      TYPE: "${TYPE}"
      VERSION: "${MINECRAFT_VERSION}"
      DIFFICULTY: "${DIFFICULTY}"
      SNOOPER_ENABLED: "false"
      VIEW_DISTANCE: "16"
      MODE: "${GAME_MODE}"
      ALLOW_FLIGHT: "true"
      GENERIC_PACK: "${MODPACK_URL}"
      REMOVE_OLD_MODS: "false"
    volumes:
      - data:/data

volumes:
  data:
    name: "${VOLUME_NAME}"
