name: minecraft_bedrock
services:
  bedrock-server:
    image: itzg/minecraft-bedrock-server:latest
    tty: true
    stdin_open: true
    ports:
      - 19132:19132/udp
    environment:
      UID: "1000"
      GID: "1000"
      EULA: "true"
      TZ: "America/Bogota"
      DIFFICULTY: "${DIFFICULTY}"
      GAMEMODE: "${GAME_MODE}"
      VIEW_DISTANCE: "16"
      VERSION: "${VERSION}"
      LEVEL_NAME: "${LEVEL_NAME}"
    volumes:
      - /home/juancmerchan/Servers/Minecraft/bedrock:/data